<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="Content-type" content="text/html;charset=UTF-8" /><link rel="shortcut icon" href="/imgs/sys/favicon.ico" type="image/x-icon" />
<title><?= $this->titlepage?> </title>

<?php echo $this->Scripts('base');?>


</head>
<body style="margin: 0; padding: 0;">

<!-- CONTAINER START -->
<div id="container">
	<!-- HEADER START -->
	<div id="headerWrapper" class="container clearfix">
		<div class="twelve columns alpha">
			<div id="logo">
				<a href="/">
					<img src="/imgs/sys/esr_logo_engine.png" width="190" height="70" alt="EatSleepRIDE.com" title="EatSleepRIDE.com">
				</a>
			</div>
			<div id="header-branding">
			</div>
		</div>	
		<div class="four columns omega">
			<ul id="headerLinks">
				<li class="top-item"><a href="">About</a>
					<ul class="headerLinks-sub-nav">
						<li class="sub-item">
							<a href="/about">About</a>	
						</li>
						<li class="sub-item">
							<a href="/contact">Contact</a>
	     				</li>
	     				<li class="sub-item">
	     					<a href="/terms">Terms</a>
	     				</li>
					</ul>
				</li>
	   			<li class="top-item"><a href="/help">Help</a>
	   			</li>
	   			<?php

   			    // If user logged in ...
			    if(Zend_Registry::get('logged') == 1)
				{
					$uid = Zend_Registry::get('uid');		
											
					echo'<li class="top-item"><a href="/settings">My Profile</a></li>';
	   			} ?> 
	   				
				<li class="top-item"><a href="/logout">Log out</a></li>
	   		</ul>
			<div class="connectLinks">
				<a href="http://twitter.com/#!/EatSleepRide/" target="_blank">
					<i id="ESRtwitter" class="icon sprite icon-twitter" title="ESR Twitter"></i>
				</a>
	          	<a href="http://www.youtube.com/user/EatSleepRideTV" target="_blank">
					<i id="ESRyoutube" class="icon sprite icon-youtube" title="ESR YouTube"></i>
				</a>
				<a href="http://www.facebook.com/ESR.cc/" target="_blank">
					<i id="ESRfacebook" class="icon sprite icon-facebook" title="ESR Facebook"></i>
				</a>
			</div>
		</div>
	</div>
	<!-- HEADER END -->
	
	<?php echo $this->layout()->content;?>
	
	<div id="popupContact">
		<a id="popupContactClose">x</a>
		<h1>Preview Content</h1>
		<div id="detailView"></div>
		<p id="contactArea"> </p>
	</div>
	<div id="backgroundPopup"></div>
	
</div>

<div id="deleteDialog"></div>


<a href='#' class="sprite" id="scroll-top" style="display:block;"><span>Scroll to Top</span></a>
<!--  CONTAINER END -->
<div id="storyPreview"></div>
</body>
</html>