<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<body>
URL:<input name="url" id="URL" value="" /><br />
Category: <input name="cat" id="cat" /><br />
<input type="hidden" id="catid" value="0" />
<input type="submit" onclick="add(this);" />
<br />
Search: <input type="search" name="srch" id="search" onkeyup="Search(this.value);" />
<div class="parent" >
<div class="wrap">
</div>
<div class="clear"></div>
</div>
</body>


